kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: mean-app-uat
bases:
  - ../../base/mean-app
resources:
  - namespace.yaml
patchesStrategicMerge:
  - patch-backend-route.yaml
  - patch-frontend-route.yaml