kind: Secret
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    template: mongodb-persistent-template
  name: mongodb
type: Opaque
data:
  database-admin-password: bW9uZ29kYg==
  database-name: Y29udGFjdGRi
  database-password: bW9uZ29kYg==
  database-user: bW9uZ29kYg==
