apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: backend
    name: backend-s2i-build
    app.kubernetes.io/name: backend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "12"
  name: backend-s2i-build
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'backend:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:12
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0