kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  labels:
    app: frontend
    name: frontend-s2i-build
    app.kubernetes.io/name: frontend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "12"
  name: frontend-s2i-build
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'frontend:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx:1.14
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0