apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: frontend
    name: frontend-jenkins-pipeline
    app.kubernetes.io/name: frontend
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "12"
  name: frontend-jenkins-pipeline
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/pittar/mean-frontend.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: APP_NAME
        value: frontend
      - name: PROJECT_BASE
        value: mean-app
      - name: GIT_SOURCE_URL
        value: https://github.com/pittar/mean-frontend.git
      - name: GIT_SOURCE_REF
        value: master
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: pPSVjgdJuYEeQGQIfPhsk3DpjbKRSSP0wu0OAo7P
    type: GitHub
  - generic:
      secret: UrcVCFHuN0vnvn8YU7Bcv02bM6gQU21MN7Qeifja
    type: Generic
status:
  lastVersion: 0